import type {
  EconomicState,
  PoliticalState,
  Institution,
  InterestGroup,
  Scenario,
  ForeignNation,
} from "./types";
import {
  GovernmentType,
  Era,
  InstitutionCategory,
  InterestGroupType,
  DiplomaticStatus,
} from "./types";

// ── Default Economic State ──────────────────────────────────────────────────

export const DEFAULT_ECONOMIC_STATE: EconomicState = {
  gdp: 1000,
  gdpGrowth: 2.0,
  population: 50,
  populationGrowth: 1.0,
  inflation: 2.0,
  unemployment: 5.0,
  taxRate: 30,
  governmentSpending: {
    defense: 3,          // 対GDP比% (平時先進国: 2-4%)
    education: 5,        // 対GDP比% (OECD平均: 4-6%)
    infrastructure: 4,   // 対GDP比% (先進国: 3-5%)
    welfare: 10,         // 対GDP比% (先進国: 8-20%)
    research: 2,         // 対GDP比% (先進国: 1.5-3%)
  },
  debt: 400,
  debtToGdpRatio: 40,
  tradeBalance: 0,
  giniCoefficient: 0.35,
  treasury: 100,
  fiscalBalance: 0,
  primaryBalance: 0,
  totalSpendingRate: 24,
  totalRevenueRate: 30,
  isWarEconomy: false,
};

export const WAR_ECONOMY_THRESHOLD = 15;

// ── Default Political State ─────────────────────────────────────────────────

export const DEFAULT_POLITICAL_STATE: PoliticalState = {
  governmentType: GovernmentType.PARLIAMENTARY_DEMOCRACY,
  legitimacy: 70,
  corruption: 30,
  stability: 60,
  unrest: 20,
  bureaucracyEfficiency: 60,
  electionCycle: 4,
  yearsSinceElection: 0,
};

// ── Initial Institutions ────────────────────────────────────────────────────

export const INITIAL_INSTITUTIONS: Institution[] = [
  // ── POLITICAL ──────────────────────────────────────────────────────────
  {
    id: "rule_of_law",
    name: "法の支配",
    description: "法律がすべての市民と政府機関に平等に適用される原則。これなくして近代国家は成立しない。「法の前の平等」は、権力の恣意的行使を防ぐ最も基本的な制度的保障である。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "安定度50以上、腐敗度50以下",
    effects: { corruption: -5, stability: 5, bureaucracyEfficiency: 3 },
    adoptionCost: 20,
    stabilityImpact: -5,
    prerequisiteIds: [],
    revocable: false,
  },
  {
    id: "free_press",
    name: "報道の自由",
    description: "メディアが政府の検閲なしに情報を発信できる制度。権力の監視機能を果たし、腐敗の抑止に大きく寄与する一方、政権批判を増大させ短期的な不安定化を招くリスクもある。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "法の支配が採用済み、正統性60以上",
    effects: { corruption: -4, legitimacy: 5, unrest: 3 },
    adoptionCost: 15,
    stabilityImpact: -8,
    prerequisiteIds: ["rule_of_law"],
    revocable: true,
  },
  {
    id: "independent_judiciary",
    name: "司法の独立",
    description: "司法機関が行政や立法から独立して機能する制度。権力分立の要であり、法の支配を実質的に担保する。独立した司法は投資家の信頼を高め、長期的な経済成長の基盤となる。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "法の支配が採用済み、安定度55以上",
    effects: { corruption: -5, stability: 4, legitimacy: 4 },
    adoptionCost: 25,
    stabilityImpact: -3,
    prerequisiteIds: ["rule_of_law"],
    revocable: false,
  },
  {
    id: "universal_suffrage",
    name: "普通選挙権",
    description: "すべての成人市民が選挙権を持つ制度。政治参加の拡大は正統性を高めるが、ポピュリズムの温床にもなりうる。歴史的には、総力戦を経験した国家で急速に普及した。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "議会制民主主義または共和制、正統性65以上",
    effects: { legitimacy: 10, unrest: -8, stability: 3 },
    adoptionCost: 20,
    stabilityImpact: -10,
    prerequisiteIds: ["rule_of_law"],
    revocable: false,
  },
  {
    id: "civil_liberties",
    name: "市民的自由の保障",
    description: "言論・集会・結社の自由など基本的人権を法的に保障する制度。市民社会の活力を引き出し、長期的には社会の創造性と適応力を高める。ただし、反体制運動も活発化しうる。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "法の支配・司法の独立が採用済み",
    effects: { legitimacy: 6, unrest: 2, gdpGrowth: 0.3, corruption: -2 },
    adoptionCost: 15,
    stabilityImpact: -5,
    prerequisiteIds: ["rule_of_law", "independent_judiciary"],
    revocable: true,
  },
  {
    id: "decentralization",
    name: "地方分権",
    description: "中央政府の権限の一部を地方政府に委譲する制度。地域の多様なニーズに応じた統治が可能になるが、国家の統一性が弱まるリスクもある。連邦制国家の基盤となる。",
    category: InstitutionCategory.POLITICAL,
    adopted: false,
    unlockConditions: "官僚機構の効率55以上、安定度50以上",
    effects: { bureaucracyEfficiency: 5, stability: 2, corruption: -2, legitimacy: 3 },
    adoptionCost: 25,
    stabilityImpact: -7,
    prerequisiteIds: ["rule_of_law"],
    revocable: true,
  },
  // ── ECONOMIC ──────────────────────────────────────────────────────────
  {
    id: "property_rights",
    name: "財産権の保護",
    description: "個人と法人の財産所有権を法的に保護する制度。ノースが指摘したように、効率的な財産権は経済発展の根本条件である。投資インセンティブを生み、資本蓄積を可能にする。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "法の支配が採用済み",
    effects: { gdpGrowth: 1.0, corruption: -2, giniCoefficient: 0.02 },
    adoptionCost: 15,
    stabilityImpact: -3,
    prerequisiteIds: ["rule_of_law"],
    revocable: false,
  },
  {
    id: "contract_enforcement",
    name: "契約執行制度",
    description: "商取引における契約の法的拘束力を保証し、違反時の救済手段を提供する制度。取引コストを劇的に低下させ、見知らぬ者同士の経済活動を可能にする近代経済の基盤。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "財産権の保護が採用済み",
    effects: { gdpGrowth: 0.6, tradeBalance: 3, corruption: -1 },
    adoptionCost: 15,
    stabilityImpact: -2,
    prerequisiteIds: ["property_rights"],
    revocable: false,
  },
  {
    id: "central_bank",
    name: "中央銀行",
    description: "通貨発行と金融政策を担う独立機関。テイラー・ルールに基づく金利政策により物価安定を図る。政治からの独立性が信認の鍵だが、政治家は常に緩和圧力をかけたがる。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "GDP500以上、財産権の保護が採用済み",
    effects: { inflation: -2, stability: 3, gdpGrowth: 0.5 },
    adoptionCost: 30,
    stabilityImpact: -3,
    prerequisiteIds: ["property_rights"],
    revocable: false,
  },
  {
    id: "free_trade",
    name: "自由貿易協定",
    description: "他国との間で関税障壁を撤廃・軽減する協定。比較優位に基づく国際分業により総生産が増加するが、国内の衰退産業労働者には大きな痛みを伴う。「集中した痛みと拡散した利益」の典型例。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "GDP800以上、貿易収支が管理可能な範囲",
    effects: { gdpGrowth: 0.8, tradeBalance: 5, unemployment: -1 },
    adoptionCost: 15,
    stabilityImpact: -5,
    prerequisiteIds: ["contract_enforcement"],
    revocable: true,
  },
  {
    id: "progressive_tax",
    name: "累進課税",
    description: "所得に応じて税率が段階的に上昇する課税制度。再分配機能により格差を是正するが、高額所得者の労働意欲や投資意欲を減退させるリスクがある。ラッファー曲線の示唆する最適税率の議論は尽きない。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "官僚機構の効率50以上",
    effects: { giniCoefficient: -0.05, treasury: 10, gdpGrowth: -0.3 },
    adoptionCost: 20,
    stabilityImpact: -5,
    prerequisiteIds: [],
    revocable: true,
  },
  {
    id: "company_law",
    name: "会社法・有限責任制度",
    description: "株式会社制度と有限責任の法的枠組み。投資家のリスクを限定することで、大規模な資本集積と冒険的な事業活動を可能にした。産業革命以降の経済成長の制度的基盤。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "財産権の保護・契約執行が採用済み",
    effects: { gdpGrowth: 0.8, giniCoefficient: 0.02, treasury: 5 },
    adoptionCost: 20,
    stabilityImpact: -2,
    prerequisiteIds: ["property_rights", "contract_enforcement"],
    revocable: false,
  },
  {
    id: "bankruptcy_law",
    name: "破産法",
    description: "債務超過に陥った企業・個人に対する法的手続き。「失敗の権利」を制度化することで再挑戦を可能にし、イノベーションを促進する。シリコンバレーの成功は寛容な破産法に支えられている。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "会社法が採用済み",
    effects: { gdpGrowth: 0.4, stability: 2 },
    adoptionCost: 10,
    stabilityImpact: -1,
    prerequisiteIds: ["company_law"],
    revocable: false,
  },
  {
    id: "antitrust_law",
    name: "独占禁止法",
    description: "市場における独占・寡占を規制し、自由競争を維持する法制度。競争なき市場は非効率と腐敗を生む。ただし、規制の対象企業は強力なロビー活動で骨抜きを図る。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "会社法が採用済み、GDP1000以上",
    effects: { gdpGrowth: 0.3, corruption: -3, giniCoefficient: -0.02 },
    adoptionCost: 15,
    stabilityImpact: -3,
    prerequisiteIds: ["company_law"],
    revocable: true,
  },
  {
    id: "land_tax",
    name: "土地税制度",
    description: "土地の所有に対して課税する制度。ヘンリー・ジョージが主張したように、土地税は経済学的に最も効率的な税である——土地は供給を増やせないため、課税が経済活動を歪めない。しかし政治的には最も困難な税でもある。",
    category: InstitutionCategory.ECONOMIC,
    adopted: false,
    unlockConditions: "財産権の保護が採用済み、官僚効率50以上",
    effects: { treasury: 12, giniCoefficient: -0.03, gdpGrowth: 0.2 },
    adoptionCost: 20,
    stabilityImpact: -8,
    prerequisiteIds: ["property_rights"],
    revocable: true,
  },
  // ── SOCIAL ────────────────────────────────────────────────────────────
  {
    id: "public_education",
    name: "公教育制度",
    description: "国家が提供する無償または低廉な教育制度。識字率の向上は民主主義の前提条件であり、人的資本の蓄積は長期成長の原動力である。ただし、その効果が現れるには一世代以上を要する。",
    category: InstitutionCategory.SOCIAL,
    adopted: false,
    unlockConditions: "教育予算GDP比4%以上、財政に余裕がある",
    effects: { gdpGrowth: 0.5, stability: 2, corruption: -2, bureaucracyEfficiency: 3 },
    adoptionCost: 25,
    stabilityImpact: -3,
    prerequisiteIds: [],
    revocable: false,
  },
  {
    id: "social_security",
    name: "社会保障制度",
    description: "国民の生活を保障する年金・医療・失業保険の制度。社会的リスクを集団で分担することで、個人の安心感と消費の安定をもたらす。一度導入すると政治的に廃止がほぼ不可能な「不可逆的制度」の典型。",
    category: InstitutionCategory.SOCIAL,
    adopted: false,
    unlockConditions: "福祉予算GDP比8%以上、累進課税が採用済み",
    effects: { unrest: -6, stability: 5, giniCoefficient: -0.04 },
    adoptionCost: 35,
    stabilityImpact: -5,
    prerequisiteIds: ["progressive_tax"],
    revocable: false,
  },
  {
    id: "public_health",
    name: "公衆衛生制度",
    description: "上下水道の整備、予防接種、感染症対策など国家主導の衛生政策。産業革命期の都市化に伴う衛生問題への対応として発展した。人口増加と労働生産性の向上に直結する。",
    category: InstitutionCategory.SOCIAL,
    adopted: false,
    unlockConditions: "公教育が採用済み、福祉予算GDP比5%以上",
    effects: { populationGrowth: 0.3, stability: 2, gdpGrowth: 0.2 },
    adoptionCost: 20,
    stabilityImpact: -2,
    prerequisiteIds: ["public_education"],
    revocable: false,
  },
  {
    id: "labor_rights",
    name: "労働者の権利保護",
    description: "最低賃金、労働時間規制、団結権の法的保障。労使間の交渉力の不均衡を是正し、社会的安定をもたらす。ただし過度な規制は雇用の柔軟性を損ない、失業率を上昇させうる。",
    category: InstitutionCategory.SOCIAL,
    adopted: false,
    unlockConditions: "法の支配が採用済み、安定度45以上",
    effects: { unrest: -5, giniCoefficient: -0.03, unemployment: 1, stability: 3 },
    adoptionCost: 15,
    stabilityImpact: -6,
    prerequisiteIds: ["rule_of_law"],
    revocable: true,
  },
  {
    id: "environmental_regulation",
    name: "環境規制",
    description: "産業活動に伴う環境破壊を規制する法制度。外部不経済の内部化というピグー税の理念に基づく。短期的には企業コストを増大させるが、長期的には持続可能な成長の基盤となる。",
    category: InstitutionCategory.SOCIAL,
    adopted: false,
    unlockConditions: "GDP800以上、公教育が採用済み",
    effects: { gdpGrowth: -0.2, stability: 2, populationGrowth: 0.1 },
    adoptionCost: 15,
    stabilityImpact: -4,
    prerequisiteIds: ["public_education"],
    revocable: true,
  },
  // ── MILITARY ──────────────────────────────────────────────────────────
  {
    id: "professional_army",
    name: "常備軍",
    description: "平時から維持される専門的な職業軍隊。中世の封建軍制から近代国家への転換を象徴する制度。高い即応性と専門性を持つが、財政的負担が大きく、軍部の政治的影響力を強化するリスクがある。",
    category: InstitutionCategory.MILITARY,
    adopted: false,
    unlockConditions: "国防費GDP比3%以上、財政に余裕がある",
    effects: { stability: 5, unrest: -3 },
    adoptionCost: 30,
    stabilityImpact: -3,
    prerequisiteIds: [],
    revocable: true,
  },
  {
    id: "conscription",
    name: "徴兵制",
    description: "市民に軍務を義務付ける制度。国民皆兵は「国民国家」の理念と不可分であり、歴史的には参政権拡大の原動力ともなった。「戦場で血を流す者に投票権を」という論理は強力である。",
    category: InstitutionCategory.MILITARY,
    adopted: false,
    unlockConditions: "人口30以上、正統性50以上",
    effects: { unrest: 5, gdpGrowth: -0.3, legitimacy: 3 },
    adoptionCost: 15,
    stabilityImpact: -8,
    prerequisiteIds: [],
    revocable: true,
  },
  {
    id: "military_academy",
    name: "士官学校",
    description: "軍事指導者を体系的に養成する教育機関。近代的な軍事ドクトリンの発展と、軍の専門職業化を促進する。多くの場合、軍事エリートは政治にも影響力を持つようになる。",
    category: InstitutionCategory.MILITARY,
    adopted: false,
    unlockConditions: "常備軍が採用済み、教育予算GDP比4%以上",
    effects: { stability: 3, bureaucracyEfficiency: 2 },
    adoptionCost: 20,
    stabilityImpact: -2,
    prerequisiteIds: ["professional_army"],
    revocable: false,
  },
  {
    id: "intelligence_agency",
    name: "情報機関",
    description: "国内外の情報収集・分析を専門とする組織。国家安全保障の根幹を担うが、監視国家化のリスクと市民的自由への脅威を内包する。「誰が監視者を監視するのか」という根源的問いが常につきまとう。",
    category: InstitutionCategory.MILITARY,
    adopted: false,
    unlockConditions: "常備軍が採用済み、腐敗度60以下",
    effects: { stability: 4, corruption: 2, unrest: -2 },
    adoptionCost: 25,
    stabilityImpact: -3,
    prerequisiteIds: ["professional_army"],
    revocable: true,
  },
];

// ── Initial Interest Groups ─────────────────────────────────────────────────

export const INITIAL_INTEREST_GROUPS: InterestGroup[] = [
  {
    id: "aristocracy",
    name: "貴族",
    type: InterestGroupType.ARISTOCRACY,
    influence: 30,
    satisfaction: 60,
    demands: ["税率の引き下げ", "財産権の保護"],
  },
  {
    id: "military",
    name: "軍部",
    type: InterestGroupType.MILITARY,
    influence: 20,
    satisfaction: 50,
    demands: ["国防費の増額", "軍の近代化"],
  },
  {
    id: "merchants",
    name: "商人",
    type: InterestGroupType.MERCHANTS,
    influence: 25,
    satisfaction: 55,
    demands: ["自由貿易の推進", "規制の緩和"],
  },
  {
    id: "workers",
    name: "労働者",
    type: InterestGroupType.WORKERS,
    influence: 25,
    satisfaction: 40,
    demands: ["賃金の引き上げ", "労働条件の改善"],
  },
  {
    id: "farmers",
    name: "農民",
    type: InterestGroupType.FARMERS,
    influence: 15,
    satisfaction: 45,
    demands: ["農業補助金", "輸入制限"],
  },
  {
    id: "intellectuals",
    name: "知識人",
    type: InterestGroupType.INTELLECTUALS,
    influence: 15,
    satisfaction: 50,
    demands: ["教育予算の増額", "研究開発の促進"],
  },
  {
    id: "bureaucrats",
    name: "官僚",
    type: InterestGroupType.BUREAUCRATS,
    influence: 20,
    satisfaction: 55,
    demands: ["予算の拡大", "人事の安定"],
  },
];

// ── Initial Foreign Nations ─────────────────────────────────────────────────

export const INITIAL_FOREIGN_NATIONS: ForeignNation[] = [
  {
    id: "iron_empire",
    name: "鉄壁帝国",
    governmentType: GovernmentType.ABSOLUTE_MONARCHY,
    militaryStrength: 85,
    economicStrength: 70,
    status: DiplomaticStatus.RIVAL,
    opinion: -20,
    tradeAgreement: false,
    alliance: false,
  },
  {
    id: "jade_federation",
    name: "翡翠連邦",
    governmentType: GovernmentType.PARLIAMENTARY_DEMOCRACY,
    militaryStrength: 50,
    economicStrength: 80,
    status: DiplomaticStatus.FRIENDLY,
    opinion: 30,
    tradeAgreement: true,
    alliance: false,
  },
  {
    id: "golden_dynasty",
    name: "黄金王朝",
    governmentType: GovernmentType.MONARCHY,
    militaryStrength: 65,
    economicStrength: 90,
    status: DiplomaticStatus.NEUTRAL,
    opinion: 5,
    tradeAgreement: false,
    alliance: false,
  },
  {
    id: "crimson_republic",
    name: "紅蓮共和国",
    governmentType: GovernmentType.REPUBLIC,
    militaryStrength: 60,
    economicStrength: 55,
    status: DiplomaticStatus.NEUTRAL,
    opinion: 0,
    tradeAgreement: false,
    alliance: false,
  },
  {
    id: "azure_alliance",
    name: "蒼穹同盟",
    governmentType: GovernmentType.CONSTITUTIONAL_MONARCHY,
    militaryStrength: 45,
    economicStrength: 65,
    status: DiplomaticStatus.FRIENDLY,
    opinion: 25,
    tradeAgreement: false,
    alliance: false,
  },
  {
    id: "dawn_principality",
    name: "暁の公国",
    governmentType: GovernmentType.FEUDAL_MONARCHY,
    militaryStrength: 55,
    economicStrength: 40,
    status: DiplomaticStatus.NEUTRAL,
    opinion: -5,
    tradeAgreement: false,
    alliance: false,
  },
  {
    id: "abyss_council",
    name: "深淵評議会",
    governmentType: GovernmentType.THEOCRACY,
    militaryStrength: 70,
    economicStrength: 50,
    status: DiplomaticStatus.HOSTILE,
    opinion: -45,
    tradeAgreement: false,
    alliance: false,
  },
];

export const GOVERNMENT_TYPE_DESCRIPTIONS: Record<GovernmentType, string> = {
  [GovernmentType.TRIBAL]: "部族の長老たちによる合議制。決定は遅いが正統性は高い。大規模な統治には不向き。",
  [GovernmentType.CHIEFDOM]: "有力な首長による支配。部族社会からの自然な発展形態。",
  [GovernmentType.MONARCHY]: "世襲の君主による統治。安定性は高いが、君主の能力に依存する。",
  [GovernmentType.FEUDAL_MONARCHY]: "封建的な主従関係に基づく分権的統治。地方貴族の自律性が高い。",
  [GovernmentType.ABSOLUTE_MONARCHY]: "君主に権力が集中した体制。迅速な意思決定が可能だが、正確な情報が上がってこないリスクがある。",
  [GovernmentType.CONSTITUTIONAL_MONARCHY]: "憲法により君主の権力が制限された体制。安定性と改革のバランスが取れる。",
  [GovernmentType.PARLIAMENTARY_DEMOCRACY]: "選挙で選ばれた議会が政府を組織する体制。正統性が高いが、選挙サイクルに左右される。",
  [GovernmentType.REPUBLIC]: "国民が主権者として代表者を選出する体制。理念的には最も正統だが、実際の運用は複雑。",
  [GovernmentType.ONE_PARTY_STATE]: "単一政党が統治する体制。長期計画が可能だが、腐敗が蓄積しやすい。",
  [GovernmentType.MILITARY_JUNTA]: "軍部が政権を掌握した体制。治安は安定するが経済的自由が制限される。",
  [GovernmentType.THEOCRACY]: "宗教的権威に基づく統治。イデオロギー的結束は強いが、世俗化への対応が課題。",
};

// ── Scenarios ───────────────────────────────────────────────────────────────

export const SCENARIOS: Scenario[] = [
  {
    id: "modern_democracy",
    name: "現代民主国家",
    description:
      "安定した議会制民主主義のもと、経済成長と社会福祉のバランスを取りながら国家を運営する。",
    startYear: 2000,
    initialState: {
      economic: { ...DEFAULT_ECONOMIC_STATE },
      political: { ...DEFAULT_POLITICAL_STATE },
    },
  },
  {
    id: "emerging_nation",
    name: "新興国の挑戦",
    description:
      "独立を果たしたばかりの新興国で、急速な近代化と経済発展を目指す。",
    startYear: 1960,
    initialState: {
      economic: {
        ...DEFAULT_ECONOMIC_STATE,
        gdp: 200,
        gdpGrowth: 4.0,
        population: 30,
        populationGrowth: 2.5,
        inflation: 6.0,
        unemployment: 12.0,
        taxRate: 20,
        governmentSpending: {
          defense: 5,
          education: 3,
          infrastructure: 3,
          welfare: 5,
          research: 1,
        },
        debt: 80,
        debtToGdpRatio: 40,
        tradeBalance: -5,
        giniCoefficient: 0.5,
        treasury: 30,
        totalSpendingRate: 17,
        totalRevenueRate: 20,
      },
      political: {
        ...DEFAULT_POLITICAL_STATE,
        governmentType: GovernmentType.ONE_PARTY_STATE,
        legitimacy: 55,
        corruption: 50,
        stability: 40,
        unrest: 35,
        bureaucracyEfficiency: 30,
        electionCycle: 0,
        yearsSinceElection: 0,
      },
    },
  },
  {
    id: "ancient_empire",
    name: "古代帝国の興亡",
    description:
      "広大な領土と大人口を持つ古代帝国を統治し、内乱や外敵から国を守る。",
    startYear: 500,
    initialState: {
      economic: {
        ...DEFAULT_ECONOMIC_STATE,
        gdp: 100,
        gdpGrowth: 0.5,
        population: 200,
        populationGrowth: 0.3,
        inflation: 1.0,
        unemployment: 10.0,
        taxRate: 25,
        governmentSpending: {
          defense: 8,
          education: 1,
          infrastructure: 2,
          welfare: 2,
          research: 0,
        },
        debt: 30,
        debtToGdpRatio: 30,
        tradeBalance: 5,
        giniCoefficient: 0.6,
        treasury: 80,
        totalSpendingRate: 13,
        totalRevenueRate: 25,
      },
      political: {
        ...DEFAULT_POLITICAL_STATE,
        governmentType: GovernmentType.MONARCHY,
        legitimacy: 75,
        corruption: 40,
        stability: 50,
        unrest: 30,
        bureaucracyEfficiency: 35,
        electionCycle: 0,
        yearsSinceElection: 0,
      },
    },
  },
  {
    id: "reform_crisis",
    name: "体制移行の苦悩",
    description:
      "一党独裁体制の崩壊後、政治的混乱と経済危機の中で新たな国家体制を築く。",
    startYear: 1991,
    initialState: {
      economic: {
        ...DEFAULT_ECONOMIC_STATE,
        gdp: 400,
        gdpGrowth: -3.0,
        population: 80,
        populationGrowth: 0.2,
        inflation: 15.0,
        unemployment: 18.0,
        taxRate: 25,
        governmentSpending: {
          defense: 4,
          education: 4,
          infrastructure: 3,
          welfare: 12,
          research: 2,
        },
        debt: 500,
        debtToGdpRatio: 125,
        tradeBalance: -10,
        giniCoefficient: 0.45,
        treasury: 20,
        totalSpendingRate: 25,
        totalRevenueRate: 25,
      },
      political: {
        ...DEFAULT_POLITICAL_STATE,
        governmentType: GovernmentType.ONE_PARTY_STATE,
        legitimacy: 30,
        corruption: 70,
        stability: 25,
        unrest: 55,
        bureaucracyEfficiency: 40,
        electionCycle: 0,
        yearsSinceElection: 0,
      },
    },
  },
];

// ── Era Thresholds ──────────────────────────────────────────────────────────

export const ERA_THRESHOLDS: { maxYear: number; era: Era }[] = [
  { maxYear: 499, era: Era.ANCIENT },
  { maxYear: 799, era: Era.CLASSICAL },
  { maxYear: 1399, era: Era.FEUDAL },
  { maxYear: 1599, era: Era.EARLY_MODERN },
  { maxYear: 1799, era: Era.ENLIGHTENMENT },
  { maxYear: 1913, era: Era.IMPERIAL },
  { maxYear: 1945, era: Era.WORLD_WAR },
  { maxYear: 1991, era: Era.COLD_WAR },
  { maxYear: 2020, era: Era.GLOBALIZATION },
  { maxYear: Infinity, era: Era.MODERN },
];

export function getEraForYear(year: number): Era {
  for (const threshold of ERA_THRESHOLDS) {
    if (year <= threshold.maxYear) {
      return threshold.era;
    }
  }
  return Era.MODERN;
}

// ── Government Type Labels ──────────────────────────────────────────────────

export const GOVERNMENT_TYPE_LABELS: Record<GovernmentType, string> = {
  [GovernmentType.TRIBAL]: "部族社会",
  [GovernmentType.CHIEFDOM]: "首長制",
  [GovernmentType.MONARCHY]: "君主制",
  [GovernmentType.FEUDAL_MONARCHY]: "封建君主制",
  [GovernmentType.ABSOLUTE_MONARCHY]: "絶対君主制",
  [GovernmentType.CONSTITUTIONAL_MONARCHY]: "立憲君主制",
  [GovernmentType.PARLIAMENTARY_DEMOCRACY]: "議会制民主主義",
  [GovernmentType.REPUBLIC]: "共和制",
  [GovernmentType.ONE_PARTY_STATE]: "一党独裁制",
  [GovernmentType.MILITARY_JUNTA]: "軍事政権",
  [GovernmentType.THEOCRACY]: "神権政治",
};

// ── Era Labels ──────────────────────────────────────────────────────────────

export const ERA_LABELS: Record<Era, string> = {
  [Era.ANCIENT]: "古代・部族社会",
  [Era.CLASSICAL]: "古典古代",
  [Era.FEUDAL]: "封建時代",
  [Era.EARLY_MODERN]: "初期近代",
  [Era.ENLIGHTENMENT]: "啓蒙と革命",
  [Era.IMPERIAL]: "帝国主義時代",
  [Era.WORLD_WAR]: "世界大戦期",
  [Era.COLD_WAR]: "冷戦期",
  [Era.GLOBALIZATION]: "グローバル化時代",
  [Era.MODERN]: "現代",
};
